const BLOCKED_MEXAS_PROXY_PATH_PATTERNS = [
  /^v0\/comment$/,
  /^v0\/comments$/,
  /^v0\/comment-thread$/,
  /^v0\/comment-threads$/,
  /^v0\/comment-reactions$/,
  /^v0\/create-post-comment$/,
  /^v0\/delete-spam-comments$/,
  /^v0\/edit-comment$/,
  /^v0\/edit-post-comment$/,
  /^v0\/get-best-comments$/,
  /^v0\/get-suspected-spam-comments$/,
  /^v0\/hide-comment$/,
  /^v0\/pin-comment$/,
  /^v0\/record-comment-view$/,
  /^v0\/update-post-comment$/,
  /^v0\/user-comments$/,
  /^v0\/get-boost-/,
  /^v0\/purchase-boost$/,
  /^v0\/remove-boost$/,
  /^v0\/admin-get-mana-sales$/,
  /^v0\/convert-cash-to-mana$/,
  /^v0\/convert-sp-to-mana$/,
  /^v0\/get-active-user-mana-stats$/,
  /^v0\/get-mana-/,
  /^v0\/managram$/,
  /^v0\/managrams$/,
  /^v0\/manalink$/,
  /^v0\/claimmanalink$/,
  /^v0\/create-idenfy-session$/,
  /^v0\/get-idenfy-status$/,
  /^v0\/get-verification-/,
  /^v0\/get-monitor-status-gidx$/,
  /^v0\/register-gidx$/,
  /^v0\/upload-document-gidx$/,
  /^v0\/get-predictle-/,
  /^v0\/save-predictle-/,
  /^v0\/admin-create-sweepstakes$/,
  /^v0\/buy-sweepstakes-/,
  /^v0\/claim-free-sweepstakes-/,
  /^v0\/claim-sweepstakes-/,
  /^v0\/select-sweepstakes-/,
  /^v0\/shop-/,
]

export function isBlockedMexasApiProxyPath(path: string) {
  return BLOCKED_MEXAS_PROXY_PATH_PATTERNS.some((pattern) => pattern.test(path))
}
